# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cooldryx
tagline:          'Blog'
description:      'A programming blog'
url:              http://cooldryx.github.io/
baseurl:          /

author:
  name:           'cooldryx'
  url:            https://github.com/cooldryx

paginate:         5

github:
  repo:           https://github.com/cooldryx/cooldryx.github.io
